# Generated by Django 4.2.6 on 2023-10-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lumapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Custom User'},
        ),
    ]
